# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install -y libopenblas-dev liblapack-dev graphviz libgraphviz-dev ninja-build
        sudo apt-get -y install mpich
        python -m pip install --upgrade pip
        pip install flake8 pytest pyyaml scikit-build
        pip install fenics-ffcx
    - name: Run local assembly
      run: |
        python run.py --form_compiler=ffcx --scalar_type=double --action --global_size=10000000 --degree 5 --problem=Mass --nrepeats 5 --cell_type=hexahedron
